### PR TITLE
New strategy for Sunrise library

### PR DESCRIPTION
**Pull request by ghost**
New strategy for my packages...

### CODE REVIEW

**Comment by sunrise-php** [comment]
My packages for PHP 7.2+. How to solve this problem?

**Comment by oscarotero** [comment]
There's the `feature/psr-17` branch, created to use the factories provided by the different packages (diactoros, guzzle, etc) and likely will be released as a new major version, removing support for php 7.0 and, maybe, php 7.1.
Note also that you don't have to create a factory class, just add your factory classes to the strategies array: https://github.com/middlewares/utils/blob/feature/psr-17/src/Factory.php#L25

**Comment by fenric** [comment]
@oscarotero class names is valid:

```
Sunrise\Http\ServerRequest\ServerRequestFactory
Sunrise\Http\Message\ResponseFactory
Sunrise\Stream\StreamFactory
Sunrise\Uri\UriFactory
```

tests is passed:

https://travis-ci.com/sunrise-php/http-server-request
https://travis-ci.com/sunrise-php/http-message
https://travis-ci.com/sunrise-php/stream
https://travis-ci.com/sunrise-php/uri

**Comment by oscarotero** [comment]
You've created this pull request from master branch. Please, use the [`feature/psr-17`](https://github.com/middlewares/utils/tree/feature/psr-17) as the base branch to add your library.

**Comment by sunrise-php** [comment]
> You've created this pull request from master branch. Please, use the [`feature/psr-17`](https://github.com/middlewares/utils/tree/feature/psr-17) as the base branch to add your library.

Something went wrong :)  Please, my new normal request:
https://github.com/middlewares/utils/pull/13

**Pull request closed without merging**
