### PR TITLE
use official PSR-15 packages

### PR DESCRIPTION
**Pull request by ecolinet**
Use official PSR-15 package instead of the interop ones

### CODE REVIEW

**Comment by oscarotero** [comment]
Thank you 👍

**Comment by ecolinet** [comment]
You're welcome. I wonder why you have the composer.lock file in the .gitignore file (?)

**Comment by oscarotero** [comment]
Because this package is installed as a dependency. IMO, lock files should exists in the root project, not in its dependencies.

**Comment by ecolinet** [comment]
You're right, but it could be useful for travis for example. And in any
case the project doesn't inherit from it. Your choice !

2018-01-23 20:49 GMT+01:00 Oscar Otero <notifications@github.com>:

**Pull request merged**
