### PR TITLE
Use the provided libraries factories

### PR DESCRIPTION
**Pull request by oscarotero**
Diactoros, Guzzle and Slim are implementing PSR-17, so remove them in this package.

### CODE REVIEW

**Comment by oscarotero** [comment]
Waiting for Guzzle v2: https://github.com/guzzle/psr7/milestone/2

**Comment by oscarotero** [comment]
And for Slim: https://github.com/slimphp/Slim-Psr7

**Comment by fenric** [comment]
> And for Slim: https://github.com/slimphp/Slim-Psr7
Not used in versions 3.x and 4.x...

https://github.com/http-interop/http-factory-slim
Conflicted with the latest Slim version...

**Comment by fenric** [comment]
Can I help? Is this the final variant?

```php
private static function getInstance(): FactoryDiscovery
{
    if (!self::$instance) {
        self::$instance = new FactoryDiscovery([
            self::DIACTOROS,
            self::GUZZLE,
            self::SLIM,
            self::NYHOLM,
            self::SUNRISE,
        ]);
    }

    return self::$instance;
}
```

Really waiting for the release :)

**Comment by oscarotero** [comment]
When guzzle and slim release their stable versions with psr-17, I'll release the new version.

**Comment by fenric** [comment]
> When guzzle and slim release their stable versions with psr-17, I'll release the new version.

Understood, many thanks for the answer. I use:

```php
Middlewares\Utils\Factory::setResponseFactory(new ResponseFactory);
Middlewares\Utils\Factory::setServerRequestFactory(new ServerRequestFactory);
Middlewares\Utils\Factory::setStreamFactory(new StreamFactory);
Middlewares\Utils\Factory::setUriFactory(new UriFactory);
```

All is well :)

**Comment by oscarotero** [comment]
To use this version temporary, you can require the `dev-feature/psr-17` version in composer.json

**Pull request merged**
